theme: jekyll-theme-minimal
title: Lista de Curadoria do Clube do Livro
description: Lista de curadoria de links e conteúdos relevantes para o clube do livro da Saphyr.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true